backend:
  name: github
  repo: toson77/tosonblog
  branch: master

publish_mode: editorial_workflow

media_folder: "source/images"
public_folder: "public/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "source/_posts"
    create: true
    slug: "{{fields.slug}}"
    identifier_field: title
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime", default: "" }
      - { label: "Categories", name: "categories", widget: "list", default: "" }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Tags", name: "tags", widget: "list", default: "" }
